apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:latest
          envFrom:
            - configMapRef:
                name: ghost-config
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: ghost-data
              mountPath: /etc/ghost/data
        - name: ghost-sql
          image: mysql:8.0
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: ghost-data
              mountPath: /etc/ghost/mysql
      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            claimName: ghost-data-pvc
