apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual-budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual-budget
  template:
    metadata:
      labels:
        app: actual-budget
    spec:
      containers:
        - name: actual-budget
          image: docker.io/actualbudget/actual-server:latest
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5006
          volumeMounts:
            - name: actual-data
              mountPath: /etc/actual-budget/data
      volumes:
        - name: actual-data
          persistentVolumeClaim:
            claimName: actual-budget-data-pvc
