apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-openvpn-dev-pvc
  namespace: openvpn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
